#!/bin/bash
set -x
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"
export TZ=/usr/share/zoneinfo/America/New_York
date
pwd
sudo bash -c env
uname -a
#########################
echo testing 1 2 3 4
#########################

date
